version: "3.7"
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./docs:/app/docs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
      - MONGO_CONN_URL=$MONGO_CONN_URL
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  react:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - django
    command: npm start
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./config:/config
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ADMIN_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ADMIN_PASS

  mongo-express:
    image: mongo-express
    restart: always
    volumes:
      - ./config:/config
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ADMIN_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ADMIN_PASS
      ME_CONFIG_MONGODB_URL: $MONGO_CONN_URL

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped