version: "3.7"
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./docs:/app/docs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  react:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - django
    command: npm start
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./config:/config
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: config/dbconfig.txt
      MONGO_INITDB_ROOT_PASSWORD_FILE: config/dbconfig.txt

  mongo-express:
    image: mongo-express
    restart: always
    volumes:
      - ./config:/config
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $ME_ADMIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ME_PASS
      ME_CONFIG_MONGODB_URL: $ME_URL