version: '3.8'

services:
  scraper:
    build: "./scraper"
    volumes:
      - "./scraper:/app/"
      - "/app/node_modules"
    stdin_open: true
    environment:
      GPG_TTY: /dev/pts/0
    init: true
    security_opt:
      - seccomp=./scraper/chrome.json
    secrets:
      - puppet-keys
      - encryption-key

secrets:
  puppet-keys:
    file: ./config/keys/env.txt
  encryption-key:
    file: ./config/keys/kyleA.gpg