version: '3.8'

services:
  scraper:
    build: "./scraper"
    volumes:
      - "./scraper:/app/"
      - "browser_dependencies:/app/node_modules"
    stdin_open: true
    environment:
      GPG_TTY: /dev/pts/0
      DISPLAY: ":1"
      XVFB_RESOLUTION: "1920x1080x16"
    ports:
      - "8081:8080"
      - "9229:9229"
      - "5900:5900"
    init: true
    secrets:
      - puppet-keys
      - encryption-key

secrets:
  puppet-keys:
    file: ./config/keys/env.txt
  encryption-key:
    file: ./config/keys/kyleA.gpg

volumes:
  browser_dependencies:

